package com.unitech.exam.mapper;

import com.unitech.exam.model.UsersInfo;
import com.unitech.exam.model.UsersInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	int countByExample(UsersInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	int deleteByExample(UsersInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	int deleteByPrimaryKey(String ndis);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	int insert(UsersInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	int insertSelective(UsersInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	List<UsersInfo> selectByExample(UsersInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	UsersInfo selectByPrimaryKey(String ndis);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	int updateByExampleSelective(@Param("record") UsersInfo record,
			@Param("example") UsersInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	int updateByExample(@Param("record") UsersInfo record,
			@Param("example") UsersInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	int updateByPrimaryKeySelective(UsersInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	int updateByPrimaryKey(UsersInfo record);
}