package com.unitech.exam.model;

import java.util.ArrayList;
import java.util.List;

public class UsersInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public UsersInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andNdisIsNull() {
			addCriterion("NDIS is null");
			return (Criteria) this;
		}

		public Criteria andNdisIsNotNull() {
			addCriterion("NDIS is not null");
			return (Criteria) this;
		}

		public Criteria andNdisEqualTo(String value) {
			addCriterion("NDIS =", value, "ndis");
			return (Criteria) this;
		}

		public Criteria andNdisNotEqualTo(String value) {
			addCriterion("NDIS <>", value, "ndis");
			return (Criteria) this;
		}

		public Criteria andNdisGreaterThan(String value) {
			addCriterion("NDIS >", value, "ndis");
			return (Criteria) this;
		}

		public Criteria andNdisGreaterThanOrEqualTo(String value) {
			addCriterion("NDIS >=", value, "ndis");
			return (Criteria) this;
		}

		public Criteria andNdisLessThan(String value) {
			addCriterion("NDIS <", value, "ndis");
			return (Criteria) this;
		}

		public Criteria andNdisLessThanOrEqualTo(String value) {
			addCriterion("NDIS <=", value, "ndis");
			return (Criteria) this;
		}

		public Criteria andNdisLike(String value) {
			addCriterion("NDIS like", value, "ndis");
			return (Criteria) this;
		}

		public Criteria andNdisNotLike(String value) {
			addCriterion("NDIS not like", value, "ndis");
			return (Criteria) this;
		}

		public Criteria andNdisIn(List<String> values) {
			addCriterion("NDIS in", values, "ndis");
			return (Criteria) this;
		}

		public Criteria andNdisNotIn(List<String> values) {
			addCriterion("NDIS not in", values, "ndis");
			return (Criteria) this;
		}

		public Criteria andNdisBetween(String value1, String value2) {
			addCriterion("NDIS between", value1, value2, "ndis");
			return (Criteria) this;
		}

		public Criteria andNdisNotBetween(String value1, String value2) {
			addCriterion("NDIS not between", value1, value2, "ndis");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("NAME is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("NAME is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("NAME =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("NAME <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("NAME >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("NAME >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("NAME <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("NAME <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("NAME like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("NAME not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("NAME in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("NAME not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("NAME between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("NAME not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("ADDRESS is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("ADDRESS is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("ADDRESS =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("ADDRESS <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("ADDRESS >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("ADDRESS >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("ADDRESS <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("ADDRESS <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("ADDRESS like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("ADDRESS not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("ADDRESS in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("ADDRESS not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("ADDRESS between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("ADDRESS not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("PHONE is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("PHONE is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("PHONE =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("PHONE <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("PHONE >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("PHONE >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("PHONE <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("PHONE <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("PHONE like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("PHONE not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("PHONE in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("PHONE not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("PHONE between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("PHONE not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andNokIsNull() {
			addCriterion("NOK is null");
			return (Criteria) this;
		}

		public Criteria andNokIsNotNull() {
			addCriterion("NOK is not null");
			return (Criteria) this;
		}

		public Criteria andNokEqualTo(String value) {
			addCriterion("NOK =", value, "nok");
			return (Criteria) this;
		}

		public Criteria andNokNotEqualTo(String value) {
			addCriterion("NOK <>", value, "nok");
			return (Criteria) this;
		}

		public Criteria andNokGreaterThan(String value) {
			addCriterion("NOK >", value, "nok");
			return (Criteria) this;
		}

		public Criteria andNokGreaterThanOrEqualTo(String value) {
			addCriterion("NOK >=", value, "nok");
			return (Criteria) this;
		}

		public Criteria andNokLessThan(String value) {
			addCriterion("NOK <", value, "nok");
			return (Criteria) this;
		}

		public Criteria andNokLessThanOrEqualTo(String value) {
			addCriterion("NOK <=", value, "nok");
			return (Criteria) this;
		}

		public Criteria andNokLike(String value) {
			addCriterion("NOK like", value, "nok");
			return (Criteria) this;
		}

		public Criteria andNokNotLike(String value) {
			addCriterion("NOK not like", value, "nok");
			return (Criteria) this;
		}

		public Criteria andNokIn(List<String> values) {
			addCriterion("NOK in", values, "nok");
			return (Criteria) this;
		}

		public Criteria andNokNotIn(List<String> values) {
			addCriterion("NOK not in", values, "nok");
			return (Criteria) this;
		}

		public Criteria andNokBetween(String value1, String value2) {
			addCriterion("NOK between", value1, value2, "nok");
			return (Criteria) this;
		}

		public Criteria andNokNotBetween(String value1, String value2) {
			addCriterion("NOK not between", value1, value2, "nok");
			return (Criteria) this;
		}

		public Criteria andDobIsNull() {
			addCriterion("DOB is null");
			return (Criteria) this;
		}

		public Criteria andDobIsNotNull() {
			addCriterion("DOB is not null");
			return (Criteria) this;
		}

		public Criteria andDobEqualTo(String value) {
			addCriterion("DOB =", value, "dob");
			return (Criteria) this;
		}

		public Criteria andDobNotEqualTo(String value) {
			addCriterion("DOB <>", value, "dob");
			return (Criteria) this;
		}

		public Criteria andDobGreaterThan(String value) {
			addCriterion("DOB >", value, "dob");
			return (Criteria) this;
		}

		public Criteria andDobGreaterThanOrEqualTo(String value) {
			addCriterion("DOB >=", value, "dob");
			return (Criteria) this;
		}

		public Criteria andDobLessThan(String value) {
			addCriterion("DOB <", value, "dob");
			return (Criteria) this;
		}

		public Criteria andDobLessThanOrEqualTo(String value) {
			addCriterion("DOB <=", value, "dob");
			return (Criteria) this;
		}

		public Criteria andDobLike(String value) {
			addCriterion("DOB like", value, "dob");
			return (Criteria) this;
		}

		public Criteria andDobNotLike(String value) {
			addCriterion("DOB not like", value, "dob");
			return (Criteria) this;
		}

		public Criteria andDobIn(List<String> values) {
			addCriterion("DOB in", values, "dob");
			return (Criteria) this;
		}

		public Criteria andDobNotIn(List<String> values) {
			addCriterion("DOB not in", values, "dob");
			return (Criteria) this;
		}

		public Criteria andDobBetween(String value1, String value2) {
			addCriterion("DOB between", value1, value2, "dob");
			return (Criteria) this;
		}

		public Criteria andDobNotBetween(String value1, String value2) {
			addCriterion("DOB not between", value1, value2, "dob");
			return (Criteria) this;
		}

		public Criteria andRdIsNull() {
			addCriterion("RD is null");
			return (Criteria) this;
		}

		public Criteria andRdIsNotNull() {
			addCriterion("RD is not null");
			return (Criteria) this;
		}

		public Criteria andRdEqualTo(Integer value) {
			addCriterion("RD =", value, "rd");
			return (Criteria) this;
		}

		public Criteria andRdNotEqualTo(Integer value) {
			addCriterion("RD <>", value, "rd");
			return (Criteria) this;
		}

		public Criteria andRdGreaterThan(Integer value) {
			addCriterion("RD >", value, "rd");
			return (Criteria) this;
		}

		public Criteria andRdGreaterThanOrEqualTo(Integer value) {
			addCriterion("RD >=", value, "rd");
			return (Criteria) this;
		}

		public Criteria andRdLessThan(Integer value) {
			addCriterion("RD <", value, "rd");
			return (Criteria) this;
		}

		public Criteria andRdLessThanOrEqualTo(Integer value) {
			addCriterion("RD <=", value, "rd");
			return (Criteria) this;
		}

		public Criteria andRdIn(List<Integer> values) {
			addCriterion("RD in", values, "rd");
			return (Criteria) this;
		}

		public Criteria andRdNotIn(List<Integer> values) {
			addCriterion("RD not in", values, "rd");
			return (Criteria) this;
		}

		public Criteria andRdBetween(Integer value1, Integer value2) {
			addCriterion("RD between", value1, value2, "rd");
			return (Criteria) this;
		}

		public Criteria andRdNotBetween(Integer value1, Integer value2) {
			addCriterion("RD not between", value1, value2, "rd");
			return (Criteria) this;
		}

		public Criteria andNotesIsNull() {
			addCriterion("NOTES is null");
			return (Criteria) this;
		}

		public Criteria andNotesIsNotNull() {
			addCriterion("NOTES is not null");
			return (Criteria) this;
		}

		public Criteria andNotesEqualTo(String value) {
			addCriterion("NOTES =", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesNotEqualTo(String value) {
			addCriterion("NOTES <>", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesGreaterThan(String value) {
			addCriterion("NOTES >", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesGreaterThanOrEqualTo(String value) {
			addCriterion("NOTES >=", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesLessThan(String value) {
			addCriterion("NOTES <", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesLessThanOrEqualTo(String value) {
			addCriterion("NOTES <=", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesLike(String value) {
			addCriterion("NOTES like", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesNotLike(String value) {
			addCriterion("NOTES not like", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesIn(List<String> values) {
			addCriterion("NOTES in", values, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesNotIn(List<String> values) {
			addCriterion("NOTES not in", values, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesBetween(String value1, String value2) {
			addCriterion("NOTES between", value1, value2, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesNotBetween(String value1, String value2) {
			addCriterion("NOTES not between", value1, value2, "notes");
			return (Criteria) this;
		}

		public Criteria andProfileIsNull() {
			addCriterion("PROFILE is null");
			return (Criteria) this;
		}

		public Criteria andProfileIsNotNull() {
			addCriterion("PROFILE is not null");
			return (Criteria) this;
		}

		public Criteria andProfileEqualTo(String value) {
			addCriterion("PROFILE =", value, "profile");
			return (Criteria) this;
		}

		public Criteria andProfileNotEqualTo(String value) {
			addCriterion("PROFILE <>", value, "profile");
			return (Criteria) this;
		}

		public Criteria andProfileGreaterThan(String value) {
			addCriterion("PROFILE >", value, "profile");
			return (Criteria) this;
		}

		public Criteria andProfileGreaterThanOrEqualTo(String value) {
			addCriterion("PROFILE >=", value, "profile");
			return (Criteria) this;
		}

		public Criteria andProfileLessThan(String value) {
			addCriterion("PROFILE <", value, "profile");
			return (Criteria) this;
		}

		public Criteria andProfileLessThanOrEqualTo(String value) {
			addCriterion("PROFILE <=", value, "profile");
			return (Criteria) this;
		}

		public Criteria andProfileLike(String value) {
			addCriterion("PROFILE like", value, "profile");
			return (Criteria) this;
		}

		public Criteria andProfileNotLike(String value) {
			addCriterion("PROFILE not like", value, "profile");
			return (Criteria) this;
		}

		public Criteria andProfileIn(List<String> values) {
			addCriterion("PROFILE in", values, "profile");
			return (Criteria) this;
		}

		public Criteria andProfileNotIn(List<String> values) {
			addCriterion("PROFILE not in", values, "profile");
			return (Criteria) this;
		}

		public Criteria andProfileBetween(String value1, String value2) {
			addCriterion("PROFILE between", value1, value2, "profile");
			return (Criteria) this;
		}

		public Criteria andProfileNotBetween(String value1, String value2) {
			addCriterion("PROFILE not between", value1, value2, "profile");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table users_info
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users_info
     *
     * @mbggenerated do_not_delete_during_merge Thu Jan 12 22:41:40 KST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}