package com.unitech.exam.model;

public class UsersInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_info.NDIS
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	private String ndis;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_info.NAME
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_info.ADDRESS
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_info.PHONE
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_info.NOK
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	private String nok;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_info.DOB
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	private String dob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_info.RD
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	private Integer rd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_info.NOTES
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	private String notes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_info.PROFILE
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	private String profile;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_info.NDIS
	 * @return  the value of users_info.NDIS
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public String getNdis() {
		return ndis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_info.NDIS
	 * @param ndis  the value for users_info.NDIS
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public void setNdis(String ndis) {
		this.ndis = ndis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_info.NAME
	 * @return  the value of users_info.NAME
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_info.NAME
	 * @param name  the value for users_info.NAME
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_info.ADDRESS
	 * @return  the value of users_info.ADDRESS
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_info.ADDRESS
	 * @param address  the value for users_info.ADDRESS
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_info.PHONE
	 * @return  the value of users_info.PHONE
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_info.PHONE
	 * @param phone  the value for users_info.PHONE
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_info.NOK
	 * @return  the value of users_info.NOK
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public String getNok() {
		return nok;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_info.NOK
	 * @param nok  the value for users_info.NOK
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public void setNok(String nok) {
		this.nok = nok;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_info.DOB
	 * @return  the value of users_info.DOB
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public String getDob() {
		return dob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_info.DOB
	 * @param dob  the value for users_info.DOB
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public void setDob(String dob) {
		this.dob = dob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_info.RD
	 * @return  the value of users_info.RD
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public Integer getRd() {
		return rd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_info.RD
	 * @param rd  the value for users_info.RD
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public void setRd(Integer rd) {
		this.rd = rd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_info.NOTES
	 * @return  the value of users_info.NOTES
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_info.NOTES
	 * @param notes  the value for users_info.NOTES
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_info.PROFILE
	 * @return  the value of users_info.PROFILE
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public String getProfile() {
		return profile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_info.PROFILE
	 * @param profile  the value for users_info.PROFILE
	 * @mbggenerated  Fri Jan 13 00:32:14 KST 2017
	 */
	public void setProfile(String profile) {
		this.profile = profile;
	}
}